package com.example.notesapp.model

data class UserResponse(
//val commandstatus: Long,
//val commandmessage: Any?,
//val companyid: Long,
//val displayname: String,
//val location: String,
//val dbname: String,
//val serverip: String,
//val dbpassword: String,
//val connstring: String,
//val compname: String,
//val logoimage: String,
//val grouplogin: String,
//val mobileno: String,
//val username: String,
//val password: String,
//val ewayuserid: String,
//val ewaypassword: String,
//val enableeway: String,
//val compgstin: String,
//val smtpfrom: String,
//val host: String,
//val port: Long,
//val emailusername: String,
//val emailpassword: String,
//val ewayurl: String,
//val divisionlogin: String,
//val logilockeruserid: Any?,
//val logilockerpassword: Any?,
//val ewborgid: Any?,

    val id: Long,
    val token: String,
)
